### ISSUE TITLE
New Langage Library: Go

### ISSUE THREAD

**Issue by dnahurnyi** [30-seconds/30_seconds_of_knowledge#81]
I would like to add new snippets about Go language. I would like to create a repo in the same way how it's already implemented for Python or C++ but need @petrovicstefanrs  approval.

**Comment by petrovicstefanrs** [comment]
Hey @dnahurnyi , the best way to start this is for you to contact @fejes713 to see how to start your a 30sec of Go repository in the same way the other 30sec repos are made. That way once the database of snippets is sufficiently large it can be implemented into the chrome extension.

**Comment by dnahurnyi** [comment]
> Hey @dnahurnyi , the best way to start this is for you to contact @fejes713 to see how to start your a 30sec of Go repository in the same way the other 30sec repos are made. That way once the database of snippets is sufficiently large it can be implemented into the chrome extension.

Thanks @petrovicstefanrs, will do!

**Comment by fejes713** [comment]
Hi, @dnahurnyi 👋 thanks for showing interest in making the official Go repository for the snippets. 

There's is an archived [starter repo](https://github.com/30-seconds/30-seconds-starter) that you can fork and make your own Go repository. 

Once the repository has enough quality content we can consider merging it into our organization and branding it as official. 

Recently we started merging all projects (supported languages) under https://www.30secondsofcode.org/ so once your repository reaches certain quality point we will be moving it there as well :) 

Hopefully, this helps! Feel free to let me know if you need anything else.
